# 비동기 처리

## 동기

**자바스크립트는 싱글스레드다.**(종업원이 1명) Node.js에서는 강제적으로 멀티 스레드를 사용할 수 있는 기능이 생겨났다. 하지만 많이는 사용하지 않는다고 한다.

### 싱글스레드

- 카페에 종업원이 1명
- JavaScript는 싱글 스레드이다.

### 멀티 스레드

- 카페에 종업원이 여러 명
- 다른 프로그래밍 언어가 대부분 지원한다.

<br>

## 비동기(Asychronous)

- 어떠한 요청을 보내면 해당 **요청의 응답에 관계 없이(응답이 돌아오지 않아도)** 바로 다음 동작이 실행된다.
- 즉, 실행중인 작업이 끝나기를 기다리지 않고 바로 다음 작업으로 넘어갈 수 있다.

```js
// 비동기식 처리 코드

const 예보 = "👮🏻‍♀️: 폭풍이 몰려오고 있으니 조심하세요🚨";
const 도망 = "🏃🏻‍♀️: 얼른 도망가야겠다!! (후다닥)";
const 폭풍 = "👻: 하하 내가 왔다💨 ... 어라 늦었네..😤";

console.log(예보);

setTimeout(() => {
  console.log(폭풍);
}, 1000);

console.log(도망);
```

- 비동기 실행 함수는 호출 스택에 아무것도 없을 때 호출 스택에 적재된다.

```jsx
const one = "1";
const two = "2";
const three = "3";

console.log(one);
setTimeout(() => {
  console.log(two);
}, 0);
console.log(three);
// 1 3 2라는 결과가 나온다.
```

<br>

## 프로미스(Promise)

- JavaScript는 비동기 처리 시 콜백 함수를 사용한다.
- 콜백 함수를 계속 중첩시키면서 콜백 지옥에 빠질 수 있고, 이를 벗어날 수 있도록 ES6에서 **Promise라는 객체**가 등장했다.
- Promise는 비동기 처리가 성공적으로 수행되면 그 결과값을, 실패하면 에러를 전달한다.

<br>

### Promise 상태

다음의 상태 중 한 상태를 가진다.

- **대기(pending)**: 요청된 후 대기 중인 상태(미완료 상태)
- **이행(fullfilled)**: 비동기 작업이 성공적으로 완료됨
- **거부(rejected)**: 비동기 작업이 실패됨

<br>

### Promise 문법

- `new Promise` 에는 실행 함수(executor)가 전달된다.
- 실행 함수의 인수 `resolve`와 `reject`는 자바스크립트 자체에서 제공하는 콜백이다.
- `resolve(value)`: 성공적으로 처리(fullfilled)가 되면 호출한다.
- `reject(error)`: 에러 발생 시(rejected) 에러 객체를 나타내는 error와 함께 호출한다.

- pending(대기상태) - resolve(해결) - fulfilled(성공)
- pending(대기상태) - reject(거부) - rejected(실패)

```js
new Promise((resolve, reject) => {
  //code
})
  .then((result) => result)
  .then((result) => result)
  .catch((err) => err)
  .finally((result) => result);
```

```js
// rejected(실패)된 Promise를 catch로 받으면 fulfilled 반환(return 값 준 경우)
// rejected(실패)된 Promise를 catch로 받으면 fulfilled 반환
let p = new Promise(function (resolve, reject) {
  // 비동기적으로 실행될 code 작성
  reject("hello world");
}).catch((메시지) => {
  alert("catch 실행!!");
  return "catch!!";
});
console.log(p);
```

<br>

### 프로미스 체이닝

- 비동기 처리로 인한 콜백 지옥을 해결하기 위해 `then, catch, finally` 메서드를 사용한다.
- `then, catch, finally`는 언제나 프로미스를 반환하므로 프로미스 체이닝을 통해 연속적으로 호출 가능하다.

```js
// resolve인데 중간에 error가 던져졌을 때
let p2 = new Promise(function (resolve, reject) {
  // 비동기적으로 실행될 코드 작성
  resolve("hello world");
  // 메세지라는 파라미터에 reslove 내에 넣은 인자값이 들어간다.
})
  .then((메시지) => {
    alert(메시지);
    return 메시지.split(" ")[0];
  })
  // 리턴 값이 다시 '메시지'로 들어간다.
  .then((메시지) => {
    alert(메시지);
    throw Error("Error 발생! 경고경고!");
    return 메시지[0];
  })
  .then((메시지) => {
    alert(메시지);
    return 메시지;
  })
  .catch((메시지) => {
    // 중간에 에러를 만나면 이걸 실행하게 된다
    console.log(메시지);
    alert("catch 실행");
  });

console.log(p2);
```

<br>

## fetch

- 비동기 네트워크 통신을 구현하기 위해 사용하는 클라이언트 사이드 **Web API**로, HTTP 요청 전송 기능을 제공한다.
- `fetch`는 프로미스를 지원하여 비동기 처리를 위한 콜백 지옥을 해결할 수 있다.
- Ajax를 지원하는 여러 기술 중 최신 기술이다.
- `fetch` 함수는 **프로미스 객체**를 반환한다.

<br>

### fetch 문법

```js
let promise = fetch(url [, options]);
```

- url: HTTP 요청을 하고자 하는 URL
- options: HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한다.

<br>

### fetch 사용하기

- `fetch` 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 프로미스를 반환한다.
- `then()`을 통하여 프로미스가 resolve한 Response 객체를 전달 받을 수 있다.
- Response 객체는 HTTP 응답을 처리하는 프로미스 기반의 다양한 메서드를 제공한다.
  [Response - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response#instance_methods)
  - `Response.json()`: 응답을 **JSON 형태**로 파싱한다.

<br>

### fetch 함수로 HTTP 요청하는 방법

```js
async function request() {
  const response = await fetch('url 기입',
  {
    method: "GET", //POST, DELETE, PATH, PUT
	  headers: {
			"Content-type": "콘텐츠 형태",
			//application/json, text/plain 등
		},
		body: JSON.stringify(
			서버에 전달할 데이터
		);
  });
  const data = await response.json();
  console.log(data);
}
request();
```

1. GET 요청

```js
// post 요청 - 생성
// JSON.stringify() 메서드는 배열이나 객체를 JSON 포맷의 문자열로 변환해준다.
async function post() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    method: "POST",
    headers: {
      "Content-type": "application/json; charset=UTF-8",
    },
    body: JSON.stringify({
      //문자열로 변환하지 않으면 에러발생
      title: "오늘의 간식",
      body: "고소미",
      userId: 3,
    }),
  });
  const data = await response.json();
  console.log(data);
}
post();
```

- `JSON.stringify()` 메서드: 배열이나 객체를 JSON 포맷의 문자열로 변환해준다.

body에 담을 콘텐츠는 반드시`JSON.stringify()` 하여 JSON 문자열 형태로 변환해야 한다. 서버로 전송이 가능한 형태로 바꾸기 위해 문자열화 작업을 해줘야 하는데, 이를 직렬화라고 한다.

> 💡 객체(Object) → 문자열(string) : 직렬화(Serialization)
>
> 💡 문자열(string) → 객체(Object) : 역직렬화(Deserialization)

2. DELETE 요청

```js
// delete - 삭제
async function delete() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts/3',
  { method: "DELETE"}
  );
  const data = await response.json();
  console.log(data);
}
delete();
```

3. PUT 요청

```js
// put - 수정
async function put() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts/1", {
    method: "PUT",
    headers: {
      "Content-type": "application/json; charset=UTF-8",
    },
    body: JSON.stringify({
      title: "오늘의 간식",
      body: "마카다미아 쿠키", //업데이트할 내용
      userId: 1, //1번 user
    }),
  });
  const data = await response.json();
  console.log(data);
}
put();
```

<br>

## async/await

- async/await를 사용하면 프로미스를 좀 더 편하게 사용할 수 있다.
- 프로미스의 then, catch, finally로 비동기 처리 결과의 후속 처리를 할 필요가 없다.

```jsx
async function f() {
  return "hello world";
}

console.log("!");
f()
  .then((메시지) => {
    alert(메시지);
    return 메시지.split(" ")[0];
  })
  .then((메시지) => {
    alert(메시지);
    return 메시지[0];
  });
console.log("!!");
```

<br>

### await

- awiat 키워드는 반드시 async 함수 내부에서 사용한다.(top-level awiat 제외)
- 비동기 처리 메서드가 수행된 상태가 될 때까지 대기하다가 완료되면 프로미스가 resolve한 처리 결과를 반환한다.
- await은 반드시 프로미스 앞에서 사용해야 한다.
- 비동기 처리 메서드가 꼭 프로미스 객체를 반환해야 `await`가 의도한 대로 동작한다.

```jsx
async function f() {
  return 100;
}

f().then(alert);
```

```jsx
// 모던 자바스크립트 예제
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000);
  });

  let result = await promise; // 프라미스가 이행될 때까지 기다림 (*)

  alert(result); // "완료!"
}

f();
```

```jsx
// 기다린 것
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000);
  });

  let result = await promise; // 프라미스가 이행될 때까지 기다림 (*)
  alert(result); // "완료!"
}

f();

/////////////////

// 기다리지 않은 것
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000);
  });

  let result = promise;
  console.log(result);
  alert(result);
}

f();
```

- 다음과 같이도 사용 가능하다.

```jsx
const productData = await fetch(`http://test.api.weniv.co.kr/mall`).then((data) => data.json());
```

<br>

## 에러 핸들링

> 에러 핸들링은 필수다.

### 에러 핸들링이 필요한 이유?

- 에러나 예외적인 상황에 대응하지 않으면 프로그램은 강제 종료된다. 이는 서비스 중단과도 직결된다.

<br>

### try, catch, finally로 에러 처리하기

- `async/await`에서 에러 핸들링을 하는 방법은 `try, catch, finally`를 사용하는 것이다.
- `finally` 코드 블록은 에러 발생과 상관없이 반드시 한번 실행된다.
- **런타임 에러**가 날 것 같은 곳에는 무조건적으로 처리하자.

  ```jsx
  try {
    // 실행할 코드(에러 발생 가능성이 있는 코드다)
  } catch (e) {
    // try 코드 블록에서 에러 발생하면 catch 코드블록 실행된다.
    // e에는 try 코드 블록에서 발생한 error 객체가 전달된다.
  } finally {
    // 에러 발생 상관없이 반드시 한번 실행된다.
  }
  ```

- `try, catch, finally` 사용했을 때와 사용하지 않았을 때 차이

  ```jsx
  // 예시
  a(); // 로고 받아오기 메서드 - by 길동
  b(); // 상품 정보 받아오기 메서드 - by 철수
  c(); // 장바구니 구현 함수 - by 둘리

  // a()에서 문제가 발생되면 b(), c()도 동작하지 않는다.
  // 이때, try/catch/finally를 사용하여야 한다!!
  ```

  ```jsx
  // 에러가 발생해도 마지막 finally를 실행하므로 서비스는 정상적으로 작동할 수 있다.
  // 대신 일부 기능이 실행이 안될 수도 있다.
  try {
    let x = 10;
    let y = 20;
    console.log(x + y + z);
  } catch (e) {
    console.error(e); // ReferenceError: z is not defined, 브라우저에서 에러를 던져준다.
    console.log(e); // ReferenceError: z is not defined
  } finally {
    console.log("finally"); // finally
  }

  let x = 10;
  let y = 20;
  console.log(x + y + z); // z가 할당되지 않았고, 서비스가 멈춰버린다.
  let z = 30;
  ```
